server:
  port: 8090

spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:mysql://localhost:3306/quizdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dm125.working
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
