server:
  port: 8080

spring:
  application:
    name: question-service
  datasource:
    url: jdbc:mysql://localhost:3306/quiz
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dm125.working
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
